name: 'Generate Update Metadata'
description: 'Creates app metadata and prepares files for S3 upload'
inputs:
  version:
    required: true
  os:
    required: true
  isMandatory:
    required: false
  accounts:
    required: true
  disabledAccounts:
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
